name: CI/CD Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v2

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      # 3️⃣ Lint code
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      # 4️⃣ Run tests
      - name: Run unit tests with nose
        run: nosetests
        env:
          DATABASE_URI: "postgresql://postgres:pgs3cr3t@postgres:5432/testdb"

      # 5️⃣ Login to IBM Cloud Container Registry
      - name: IBM Cloud Login
        uses: ibm-cloud/setup-ibmcloud@v1
        with:
          ibmcloud_api_key: ${{ secrets.ICR_API_KEY }}
          region: us-south

      - name: Set ICR Namespace
        run: ibmcloud cr login

      # 6️⃣ Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t us.icr.io/$
